branches:
  only:
  - master
  - dev
  - "/[v]\\d\\.\\d\\.\\d/"
cache: pip
deploy:
  provider: pypi
  user: mkolarek
  password:
    secure: i4uVryjncQPX7AnPme/b3gM7308Q6UwUvlfimLjRWHD3hjsDAKIvSjjwqqdoi1uWZ1HDaz8WpFU1+3vBnlBImB6Nm2aWbg1MzVKHiIqYhTEA6My3bny502oDNL96kS6iHPdrnuFLGdp4zaVZ+TC1n0DfTi74QqKIis9LAOme4fJAxIH3Tk40DsnOrjykVvRMCXB0m/MFhjd8gd7T2+QpXCqVZ5Et8wRKphf9FaC/E22gN65xWujP9+O7YfET4ZX3Z04jFa/aYFCuOGQEYD2Usq7M510VhQurdJRAymO14IjLMh6xvDN1lYesp373CM4rw3crAZ8o6KYsOY6CDhDtcBvW8UUG1hhLudIK9236nj8Tujk9X2njmcRx5KF+YXniYQ05f/9/FyvTYN025sdkI3ZIyNeE2xIX00ssGA6dFfBJlp/zbHifdrzg0G75MZzwLbwCr/4T7gQBB1P6wch/Qx/djy7RKRcucGJh9+bgKKkacdiLX/wODfWwD1JK1CZ2mXuMZ9oPNHMy6dAtWQLpiaoTSiDqG5aUBzuLS+a9ABBvLX4u6loL4Bn/XvU3vwIJ6HObeFz563CGUGux64nATK/196cdFFeJxKtXEV5SE1xLLqP6gYLswADAyC9/CnanWm/SRhoe14CW+bdRMO3sE74zFu06FbufPUjDSd/OZSc=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: zalando/expan
env:
- TOXENV=py
install:
- pip install tox coveralls
- pip install -r requirements_tox_test.txt
language: python
python:
- 2.7
- 3.6
script: tox
after_success:
- coveralls
